# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sina/devel/catkin_ws/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sina/devel/catkin_ws/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/sina/devel/catkin_ws/src && $(CMAKE_COMMAND) -E cmake_progress_start /home/sina/devel/catkin_ws/src/CMakeFiles /home/sina/devel/catkin_ws/src/sgaussians/CMakeFiles/progress.marks
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 sgaussians/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sina/devel/catkin_ws/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 sgaussians/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 sgaussians/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 sgaussians/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/sina/devel/catkin_ws/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
sgaussians/CMakeFiles/Tester.dir/rule:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 sgaussians/CMakeFiles/Tester.dir/rule
.PHONY : sgaussians/CMakeFiles/Tester.dir/rule

# Convenience name for target.
Tester: sgaussians/CMakeFiles/Tester.dir/rule
.PHONY : Tester

# fast build rule for target.
Tester/fast:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/Tester.dir/build.make sgaussians/CMakeFiles/Tester.dir/build
.PHONY : Tester/fast

# Convenience name for target.
sgaussians/CMakeFiles/sgaussians.dir/rule:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f CMakeFiles/Makefile2 sgaussians/CMakeFiles/sgaussians.dir/rule
.PHONY : sgaussians/CMakeFiles/sgaussians.dir/rule

# Convenience name for target.
sgaussians: sgaussians/CMakeFiles/sgaussians.dir/rule
.PHONY : sgaussians

# fast build rule for target.
sgaussians/fast:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/build
.PHONY : sgaussians/fast

src/CDDynamics.o: src/CDDynamics.cpp.o
.PHONY : src/CDDynamics.o

# target to build an object file
src/CDDynamics.cpp.o:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/CDDynamics.cpp.o
.PHONY : src/CDDynamics.cpp.o

src/CDDynamics.i: src/CDDynamics.cpp.i
.PHONY : src/CDDynamics.i

# target to preprocess a source file
src/CDDynamics.cpp.i:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/CDDynamics.cpp.i
.PHONY : src/CDDynamics.cpp.i

src/CDDynamics.s: src/CDDynamics.cpp.s
.PHONY : src/CDDynamics.s

# target to generate assembly for a file
src/CDDynamics.cpp.s:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/CDDynamics.cpp.s
.PHONY : src/CDDynamics.cpp.s

src/GMRDynamics.o: src/GMRDynamics.cpp.o
.PHONY : src/GMRDynamics.o

# target to build an object file
src/GMRDynamics.cpp.o:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/GMRDynamics.cpp.o
.PHONY : src/GMRDynamics.cpp.o

src/GMRDynamics.i: src/GMRDynamics.cpp.i
.PHONY : src/GMRDynamics.i

# target to preprocess a source file
src/GMRDynamics.cpp.i:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/GMRDynamics.cpp.i
.PHONY : src/GMRDynamics.cpp.i

src/GMRDynamics.s: src/GMRDynamics.cpp.s
.PHONY : src/GMRDynamics.s

# target to generate assembly for a file
src/GMRDynamics.cpp.s:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/GMRDynamics.cpp.s
.PHONY : src/GMRDynamics.cpp.s

src/Gaussians.o: src/Gaussians.cpp.o
.PHONY : src/Gaussians.o

# target to build an object file
src/Gaussians.cpp.o:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/Gaussians.cpp.o
.PHONY : src/Gaussians.cpp.o

src/Gaussians.i: src/Gaussians.cpp.i
.PHONY : src/Gaussians.i

# target to preprocess a source file
src/Gaussians.cpp.i:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/Gaussians.cpp.i
.PHONY : src/Gaussians.cpp.i

src/Gaussians.s: src/Gaussians.cpp.s
.PHONY : src/Gaussians.s

# target to generate assembly for a file
src/Gaussians.cpp.s:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/Gaussians.cpp.s
.PHONY : src/Gaussians.cpp.s

src/ThirdPoly.o: src/ThirdPoly.cpp.o
.PHONY : src/ThirdPoly.o

# target to build an object file
src/ThirdPoly.cpp.o:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/ThirdPoly.cpp.o
.PHONY : src/ThirdPoly.cpp.o

src/ThirdPoly.i: src/ThirdPoly.cpp.i
.PHONY : src/ThirdPoly.i

# target to preprocess a source file
src/ThirdPoly.cpp.i:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/ThirdPoly.cpp.i
.PHONY : src/ThirdPoly.cpp.i

src/ThirdPoly.s: src/ThirdPoly.cpp.s
.PHONY : src/ThirdPoly.s

# target to generate assembly for a file
src/ThirdPoly.cpp.s:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/ThirdPoly.cpp.s
.PHONY : src/ThirdPoly.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/Tester.dir/build.make sgaussians/CMakeFiles/Tester.dir/src/main.cpp.o
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/Tester.dir/build.make sgaussians/CMakeFiles/Tester.dir/src/main.cpp.i
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/Tester.dir/build.make sgaussians/CMakeFiles/Tester.dir/src/main.cpp.s
	cd /home/sina/devel/catkin_ws/src && $(MAKE) -f sgaussians/CMakeFiles/sgaussians.dir/build.make sgaussians/CMakeFiles/sgaussians.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Tester"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... sgaussians"
	@echo "... test"
	@echo "... src/CDDynamics.o"
	@echo "... src/CDDynamics.i"
	@echo "... src/CDDynamics.s"
	@echo "... src/GMRDynamics.o"
	@echo "... src/GMRDynamics.i"
	@echo "... src/GMRDynamics.s"
	@echo "... src/Gaussians.o"
	@echo "... src/Gaussians.i"
	@echo "... src/Gaussians.s"
	@echo "... src/ThirdPoly.o"
	@echo "... src/ThirdPoly.i"
	@echo "... src/ThirdPoly.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/sina/devel/catkin_ws/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

